#!/usr/bin/env bash

set -eo pipefail

get() {
  curl -s "https://raw.githubusercontent.com/SlayterDev/RadiumBrowser/master/RadiumBrowser/$1.json"
}

jq -cs 'reduce .[] as $x ([]; . + $x)' \
  <(get adServerHosts)   \
  <(get adaway)          \
  <(get blackHosts)      \
  <(get camelon)         \
  <(get malwareHosts)    \
  <(get simpleAds)       \
  <(get tracker)         \
  <(get ultimateAdBlock) \
  <(get zeus)            \
  > Multi.app/Contents/Resources/blocklist.json
