#!/usr/bin/env bash

set -eo pipefail

APP_BUNDLE_ID=`echo "$MULTI_APP_NAME" | sed -e 's/[^a-zA-Z0-9.]/-/g'`
APP_LOCATION="/Applications/Multi/$MULTI_APP_NAME.app"
ICON_TMP_DIR="`mktemp -d`/Icon.iconset"
RESOURCES=`dirname $0`

bold() {
  echo -e "\n`tput bold`$1`tput sgr0`\n"
}

if [[ -z "$MULTI_APP_NAME" ]]; then
  bold "USAGE: MULTI_APP_NAME=xxx `basename "$0"`"
  echo "Create a custom, lightweight macOS app from a group of websites."
  echo "All options are passed as environment variables:"
  echo ""
  echo "  MULTI_APP_NAME     Required"
  echo "  MULTI_ICON_PATH    Optional  PNG path to icon image"
  echo "  MULTI_JSON_CONFIG  Optional  Configuration as a JSON string"
  echo "  MULTI_OVERWRITE    Optional  Set to "1" to replace an existing Multi app with the same name"
  echo ""
  echo "Further documentation at <https://github.com/hkgumbs/multi#documentation>"
  exit 1

elif [[ -e "$APP_LOCATION" ]]; then
  if [[ "$MULTI_OVERWRITE" -ne "1" ]]; then
    bold "ERROR: \"$APP_LOCATION\" already exists!"
    if [[ -z "$MULTI_UI" ]];
    then echo "Rerun with MULTI_OVERWRITE=1 to replace it."
    else echo "You can make this change via the preferences in \"$MULTI_APP_NAME\""
    fi
    exit 1
  fi

else
  echo "Creating \"$APP_LOCATION\" ..."
  mkdir -p "$APP_LOCATION/Contents/Resources"
  chmod +x "$APP_LOCATION"
fi

echo "Generating Multi artifacts ..."
cp "$RESOURCES/Stub" "$APP_LOCATION/Stub"
cp "$RESOURCES/Stub.plist" "$APP_LOCATION/Contents/Info.plist"
sed -e "s/{{name}}/$MULTI_APP_NAME/g" -e "s/{{id}}/$APP_BUNDLE_ID/g" -i '' "$APP_LOCATION/Contents/Info.plist"
echo "$MULTI_JSON_CONFIG" > "$APP_LOCATION/Contents/Resources/config.json"

if [[ -z "$MULTI_ICON_PATH" || "${MULTI_ICON_PATH##*.}" -ne "png" ]]; then
  bold "WARNING: Skipping icon creation because no PNG provided ..."
else
  mkdir "$ICON_TMP_DIR"
  sips -z 16   16   "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_16x16.png"      > /dev/null
  sips -z 32   32   "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_16x16@2x.png"   > /dev/null
  sips -z 32   32   "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_32x32.png"      > /dev/null
  sips -z 64   64   "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_32x32@2x.png"   > /dev/null
  sips -z 128  128  "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_128x128.png"    > /dev/null
  sips -z 256  256  "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_128x128@2x.png" > /dev/null
  sips -z 256  256  "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_256x256.png"    > /dev/null
  sips -z 512  512  "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_256x256@2x.png" > /dev/null
  sips -z 512  512  "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_512x512.png"    > /dev/null
  sips -z 1024 1024 "$MULTI_ICON_PATH" --out "$ICON_TMP_DIR/icon_512x512@2x.png" > /dev/null
  iconutil -c icns --output "$APP_LOCATION/Contents/Resources/Icon.icns" "$ICON_TMP_DIR"
fi

if [[ ! -z "$MULTI_REPLACE_PID" ]]; then
  echo "Launching ..."
  kill "$MULTI_REPLACE_PID"
  open -n "$APP_LOCATION"
fi

echo "Done!"
